### PR TITLE
Just absolutely fixed the entire theme in 1 shot.

### PR DESCRIPTION
**Pull request by PhoenixAceVFX**
Since discord updated a shit ton and broke everything this PR will FIX everything :3

### CODE REVIEW

**Comment by PhoenixAceVFX** [comment]
correction, it SHOULD fix everything, not 100% but its the best i got

**Comment by ItsTatsuya** [comment]
u didnt had to do this btw, crearts v3 is going to replace this

**Comment by PhoenixAceVFX** [comment]
I know I didn't have to do it but I did it mainly because I was generally bored as well as I was actually using this theme when it busted.

**Comment by ItsTatsuya** [comment]
same i also fixed the theme myself

**Pull request closed without merging**
